import DS from 'ember-data';

export default DS.Model.extend({
    birthdate: DS.attr('date'),
    bundleId: DS.attr(),
    createdAt: DS.attr(),
    deathdate: DS.attr('date'),
    description: DS.attr('string'),
    descriptionCategory: DS.attr('string'),
    effectiveTime: DS.attr('date'),
    encounters: DS.attr(),
    ethnicity: DS.attr(),
    expectedValues: DS.attr(),
    expired: DS.attr('boolean'),
    first: DS.attr('string'),
    gender: DS.attr('string'),
    insuranceProviders: DS.attr(),
    isShared: DS.attr('boolean'),
    languages: DS.attr(),
    last: DS.attr('string'),
    maritalStatus: DS.attr('string'),
    measureId: DS.belongsTo('measure', {async: false}),
    measureIds: DS.attr(),
    measurePeriodEnd: DS.attr('date'),
    measurePeriodStart: DS.attr('date'),
    medicalRecordAssigner: DS.attr(),
    medicalRecordNumber: DS.attr(),
    notes: DS.attr(),
    originData: DS.attr(),
    race: DS.attr(),
    religiousAffiliation: DS.attr(),
    sourceDataCriteria: DS.attr(),
    testId: DS.attr(),
    title: DS.attr('string'),
    type: DS.attr('string'),
    updatedAt: DS.attr('date'),
    userId: DS.attr()
});
